-- MySQL Script generated by MySQL Workbench
-- Sat Nov 22 14:32:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fit_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fit_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fit_manager` DEFAULT CHARACTER SET utf8 ;
USE `fit_manager` ;

-- -----------------------------------------------------
-- Table `fit_manager`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fit_manager`.`plano` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `nome_plano` VARCHAR(45) NOT NULL,
  `duracao_plano` INT(3) NOT NULL,
  `valor_plano` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_plano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fit_manager`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fit_manager`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(200) NOT NULL,
  `dt_nasc_cliente` DATE NOT NULL,
  `cpf_cliente` CHAR(11) NOT NULL,
  `endereco_aluno` VARCHAR(255) NULL,
  `telefone_aluno` VARCHAR(20) NULL,
  `id_plano` INT NULL,
  `plano_id_plano` INT NOT NULL,
  PRIMARY KEY (`id_aluno`, `plano_id_plano`),
  INDEX `fk_aluno_plano_idx` (`plano_id_plano` ASC) ,
  CONSTRAINT `fk_aluno_plano`
    FOREIGN KEY (`plano_id_plano`)
    REFERENCES `fit_manager`.`plano` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
